### PR TITLE
Changed connection string access modifier to private static and added…

### PR DESCRIPTION
**Pull request by sacredgeometry**
… a setter that allows you to configure the built in ExternalLoginStore connectionstring. This prevents the need to reimplement it to get the exact same feature set.

### CODE REVIEW

**Comment by sacredgeometry** [comment]
Oops sorry, apparently nuget didn't grab the references to Umbraco core.

**Comment by Shazwazza** [comment]
Cool, yup this can be an easy work around for now until i get off my arse and find time to just make this as part of the Umbraco db :) 

Are you able to re-push your changes to exclude the packages.config.new.20160609111907 file?

**Comment by sacredgeometry** [comment]
Sorry, I was on lunch, of course I will do that now.

**Comment by Shazwazza** [comment]
Going to close this PR as this supercedes it: https://github.com/Shazwazza/UmbracoIdentity/issues/62 
The ExternalLoginStore has a few overloads now but by default it will just use Umbraco's DB, i'll write up notes about how to configure this to a different db if required.

**Pull request closed without merging**
