### PR TITLE
issue-58 add sqlSyntaxProvider to the GetTableDefinition call

### LINKED ISSUE #58: UmbracoIdentity TargetParameterCountException
When installing UmbracoIdentity on umbraco 7.5.6, you get exceptions see this forum post: https://our.umbraco.org/forum/extending-umbraco-and-using-the-api/81947-umbracoidentity-targetparametercountexception

> If you look at the stack trace, the externalLoginStore on line 146 and 147 is
> 
> ```
>var defFactoryType = Type.GetType("Umbraco.Core.Persistence.DatabaseModelDefinitions.DefinitionFactory,Umbraco.Core", true);
> var tableDefinition = (TableDefinition)defFactoryType.CallStaticMethod("GetTableDefinition", modelType);
> ```
> On this commit on the core a new parameter was added, making umbraco incompatible with UmbracoIdentity.

### PR DESCRIPTION
**Pull request by dampee**
Untested, but pretty sure i'll work. Should fix #58

### CODE REVIEW

**Comment by dampee** [comment]
Worked on some small changes to use the DatabaseSchemaHelper instead of reflection: https://github.com/dampee/UmbracoIdentity/tree/feature/useDatabaseSchemaHelper

**Comment by ruskom** [comment]
Hi Shannon,

Is it possible to apply this pull request and release a version before v5.0.0, because this issue breaks Umbraco 7.5.6 (which is the current SaaS version). 
UmbracoIdentity is a great package, we like it very much. But we had to build it from Damiaan's repo for ourselves to make our Umbraco Cloud instance work.
Let me kindly ask you to release an interim version.

Thank you in advance.
Marton

**Comment by Shazwazza** [comment]
How can i release it before 5.0.0 ? This is a breaking change because it requires a higher umbraco minimum version to work

**Comment by ruskom** [comment]
@Shazwazza thanks for your efforts.

**Pull request merged**
